const FormActionType = {
  UPDATE_TYPE: 'UPDATE_TYPE',
  UPDATE_STRATEGY_TYPE: 'UPDATE_STRATEGY_TYPE',
  UPDATE_INPUT: 'UPDATE_INPUT',
  UPDATE_DEPTH_INPUT: 'UPDATE_DEPTH_INPUT',
  UPDATE_PLAN_INPUT: 'UPDATE_PLAN_INPUT',
  UPDATE_TRACK_INPUT: 'UPDATE_TRACK_INPUT',
  UPDATE_ICEBERG_INPUT: 'UPDATE_ICEBERG_INPUT',
  UPDATE_TIME_WEIGHT_INPUT: 'UPDATE_TIME_WEIGHT_INPUT',
  UPDATE_WARNING: 'UPDATE_WARNING',
  SUBMIT_ORDER: 'SUBMIT_ORDER',
  SUBMIT_ORDER_SUCCESS: 'SUBMIT_ORDER_SUCCESS',
  SUBMIT_ORDER_ERROR: 'SUBMIT_ORDER_ERROR',
  DISABLED_SUBMIT: 'DISABLED_SUBMIT',
};
export default FormActionType;
