const WalletActionType = {
  UPDATE_CREATE_STEP: 'UPDATE_CREATE_STEP',
  UPDATE_IS_SHOW_SAFE_TIP: 'UPDATE_IS_SHOW_SAFE_TIP',
  UPDATE_IS_PASS: 'UPDATE_IS_PASS',
  UPDATE_MNEMONIC: 'UPDATE_MNEMONIC',
  UPDATE_PRIVATE: 'UPDATE_PRIVATE',
  UPDATE_KEYSTORE: 'UPDATE_KEYSTORE',
};
export default WalletActionType;
