
const CommonActionType = {
  SET_OKCHAIN_CLIENT: 'SET_OKCHAIN_CLIENT', // 设置okchain客户端
  SET_PRIVATE_KEY: 'SET_PRIVATE_KEY', // 设置私钥
  UPDATE_CURRENCY_LIST: 'UPDATE_CURRENCY_LIST', // 货币列表
  UPDATE_CURRENCY_ID: 'UPDATE_CURRENCY_ID', // 货币id
  UPDATE_CURRENCY_OBJ: 'UPDATE_CURRENCY_OBJ', // 货币obj
  UPDATE_LATEST_HEIGHT: 'UPDATE_LATEST_HEIGHT', // 更新OKChain区块最新高度
};
export default CommonActionType;
