const LocalNodeActionType = {
  UPDATE_LOGS: 'UPDATE_LOGS',
  UPDATE_OKCHAIND: 'UPDATE_OKCHAIND',
  UPDATE_IS_STARTED: 'UPDATE_IS_STARTED',
  UPDATE_P2P: 'UPDATE_P2P',
  UPDATE_REST: 'UPDATE_REST',
  UPDATE_WS: 'UPDATE_WS',
  UPDATE_DATADIR: 'UPDATE_DATADIR',
  UPDATE_DB: 'UPDATE_DB',
  UPDATE_IS_SYNC: 'UPDATE_IS_SYNC',
  UPDATE_LOCAL_HEIGHT: 'UPDATE_LOCAL_HEIGHT',
  UPDATE_ESTIMATED_TIME: 'UPDATE_ESTIMATED_TIME',
};

export default LocalNodeActionType;
