const NodeActionType = {
  UPDATE_CURRENT_NODE: 'UPDATE_CURRENT_NODE', // 更新当前节点
  UPDATE_REMOTE_LIST: 'UPDATE_REMOTE_LIST',
  UPDATE_CUSTOM_LIST: 'UPDATE_CUSTOM_LIST',
  UPDATE_BREAK_TIME: 'UPDATE_BREAK_TIME',
  UPDATE_TEMP_BREAK_TIME: 'UPDATE_TEMP_BREAK_TIME',
};

export default NodeActionType;
