const CommonActionType = {
  SET_OKEXCHAIN_CLIENT: 'SET_OKEXCHAIN_CLIENT',
  SET_PRIVATE_KEY: 'SET_PRIVATE_KEY',
  UPDATE_CURRENCY_LIST: 'UPDATE_CURRENCY_LIST',
  UPDATE_CURRENCY_ID: 'UPDATE_CURRENCY_ID',
  UPDATE_CURRENCY_OBJ: 'UPDATE_CURRENCY_OBJ',
  UPDATE_LATEST_HEIGHT: 'UPDATE_LATEST_HEIGHT',
  WALLET_CONNECT_QRCODE: 'WALLET_CONNECT_QRCODE',
};
export default CommonActionType;
