const CommonActionType = {
  SET_OKEXCHAIN_CLIENT: 'SET_OKEXCHAIN_CLIENT',
  SET_PRIVATE_KEY: 'SET_PRIVATE_KEY',
  UPDATE_CURRENCY_LIST: 'UPDATE_CURRENCY_LIST',
  UPDATE_CURRENCY_ID: 'UPDATE_CURRENCY_ID',
  UPDATE_CURRENCY_OBJ: 'UPDATE_CURRENCY_OBJ',
  UPDATE_LATEST_HEIGHT: 'UPDATE_LATEST_HEIGHT',
  ACTIVEDMENU: 'ACTIVEDMENU'
};
export default CommonActionType;
