const OrderActionType = {
  UPDATE_ORDER_TYPE: 'UPDATE_ORDER_TYPE',
  UPDATE_ORDER_PERIOD_INTERVAL: 'UPDATE_ORDER_PERIOD_INTERVAL',
  UPDATE_HIDE_OTHERS: 'UPDATE_HIDE_OTHERS',
  UPDATE_HIDE_ORDERS: 'UPDATE_HIDE_ORDERS',
  UPDATE_ENTRUST_TYPE: 'UPDATE_ENTRUST_TYPE',
  UPDATE_DATA: 'UPDATE_DATA',
};
export default OrderActionType;
