const SpotActionType = {
  FETCH_SUCCESS_CURRENCY_LIST: 'FETCH_SUCCESS_CURRENCY_LIST',
  FETCH_ERROR_CURRENCY_LIST: 'FETCH_ERROR_CURRENCY_LIST',
  UPDATE_WS_STATUS_V3: 'UPDATE_WS_STATUS_V3',
  UPDATE_WS_ERR_COUNTER_V3: 'UPDATE_WS_ERR_COUNTER_V3',
  UPDATE_WS_IS_DELAY: 'UPDATE_WS_IS_DELAY',
  FETCH_SUCCESS_TICKERS: 'FETCH_SUCCESS_TICKERS',
  UPDATE_TICKERS: 'UPDATE_TICKERS',
  FETCH_SUCCESS_INDEX_ALL: 'FETCH_SUCCESS_INDEX_ALL',
  UPDATE_ACTIVE_MARKET: 'UPDATE_ACTIVE_MARKET',
  UPDATE_SEARCH: 'UPDATE_SEARCH',
  UPDATE_SYMBOL: 'UPDATE_SYMBOL',
  COLLECT_PRODUCT: 'COLLECT_PRODUCT',
  UPDATE_BILL_MENU: 'UPDATE_BILL_MENU',

  UPDATE_THEME: 'UPDATE_THEME',
  UPDATE_CNY_RATE: 'UPDATE_CNY_RATE',

  UPDATE_HAS_OPEN_MARGIN: 'UPDATE_HAS_OPEN_MARGIN',
};
export default SpotActionType;
